### ISSUE TITLE
Support GitHub refresh tokens

### ISSUE THREAD

**Issue by spatel-cog** [frankie567/httpx-oauth#314]
The REFRESH_ENDPOINT for github is ```https://github.com/login/oauth/access_token```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/frankie567) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/frankie567/httpx-oauth/issues/314">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/frankie567/httpx-oauth/issues/314/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/frankie567/httpx-oauth/issues/314/pledge.svg">
</picture>
</a>

**Comment by frankie567** [comment]
Refreshing tokens in GitHub is quite new and still a preview feature: https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/refreshing-user-access-tokens

That's why we don't have it currently in our client. But I'm willing to review PR for it; especially if it's able to support GitHub apps with and without refresh tokens support.

**Comment by frankie567** [comment]
Closed by c8229eef702a2272a4a8b3aa52909fd4c47778c4
